#ifndef SRC_GRAPHICSEDITOR_UTILS_H_
#define SRC_GRAPHICSEDITOR_UTILS_H_

G_BEGIN_DECLS

typedef enum
{
  GRAPHICSEDITOR_DRAWING_MODE_NONE,
  GRAPHICSEDITOR_DRAWING_MODE_DDA_LINE,
  GRAPHICSEDITOR_DRAWING_MODE_BRESENHAM_LINE,
  GRAPHICSEDITOR_DRAWING_MODE_WU_LINE,
  GRAPHICSEDITOR_DRAWING_MODE_HYPERBOLE
} GraphicsEditorDrawingModeType;

G_END_DECLS

#endif /* SRC_GRAPHICSEDITOR_UTILS_H_ */
